name: Build Electron

on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm run build        # React bundle → dist/
      - run: npm run pack:electron
      - uses: actions/upload-artifact@v4
        with:
          name: clarity_engine-desktop
          path: packages/veil-electron/out/*.zip
