openapi: 3.1.0
info:
  title: SIGMA VEIL Ritual Command API
  version: 1.0.0
  description: >
    API representing operational ritual commands from the CLARITY OR DEATH system,
    enabling invocation of veil, spells, and judgment cycles via programmable interfaces.
servers:
  - url: https://clarity.engine/veil
paths:
  /veil:
    post:
      summary: Let the veil decide next action
      operationId: invokeVeil
      responses:
        '200':
          description: Ritual action determined by SIGMA VEIL
